// React/Project/client/Car-Shop/src/components/User/Register.jsx
import AuthContext from '../../contexts/authContext';
import useForm from '../../hooks/useForm';
import '../styles/User/Register.css';
import React, { useContext, useState, useEffect } from 'react';
export default function Register() {

    const isFormValid = () => {
        return values.username.trim() !== ''
            && values.password.trim() !== ''
            && values.email.trim() !== ''
            && values.repeatPassword.trim() !== '';
    };
    const {
        registerSubmitHandler,
        registerError,
        clearError
    } = useContext(AuthContext);
    const { values, onChange, onSubmit } = useForm(registerSubmitHandler, {
        username: '',
        email: '',
        password: '',
        repeatPassword: ''
    })
    useEffect(() => {
        return () => { clearError() }
    }, [])
    return (
        <form className="signup-form" onSubmit={onSubmit}>
            <h2>Sign Up</h2>
            <label htmlFor="signup-username">Username</label>
            <input
                type="text"
                id="signup-username"
                name="username"
                value={values.username}
                onChange={onChange}
                required />

            <label htmlFor="signup-email">Email</label>
            <input type="email"
                id="signup-email"
                name="email"
                value={values.email}
                onChange={onChange}
                required />

            <label htmlFor="signup-password">Password</label>
            <input type="password"
                id="signup-password"
                name="password"
                value={values.password}
                onChange={onChange}
                required />

            <label htmlFor="signup-repeat-password">Repeat Password</label>
            <input type="password"
                id="signup-repeat-password"
                name="repeatPassword"
                value={values.repeatPassword}
                onChange={onChange}
                required />

            <button type="submit" disabled={!isFormValid()}>Sign Up</button>
            {registerError && (
                <div className='register-error-container'>
                    <p className='error'>{registerError}</p>
                </div>
            )}
        </form>
    )
}

// disabled={!isFormValid()}

// Angular/Project/Crypto/src/app/user/register/register.component.ts
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
register(form: NgForm):void{
  console.log(form.value)
}
}

<div class="container">
  <h2>Registration Form</h2>

  <form #form="ngForm" (ngSubmit)="register(form)">

    <!-- Username  -->
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" placeholder="Enter your username" ngModel required
      #username="ngModel" minlength="6" maxlength="15">

    <ng-container *ngIf="username.touched">
      <p class="error" *ngIf="username.errors?.['required']">Username is required</p>
      <p class="error" *ngIf="username.errors?.['minlength']">Username must be at least
        {{username.errors?.['minlength']['requiredLength']}} characters!</p>
        <p class="error" *ngIf="username.errors?.['maxlength']">Username must be less than
          {{username.errors?.['minlength']['requiredLength']}} characters!</p>
    </ng-container>

    <!-- Email  -->
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" placeholder="Enter your email" ngModel required #email="ngModel">

    <ng-container *ngIf="email.touched">
      <p class="error" *ngIf="email.errors?.['required']">Email is required</p>
    </ng-container>

    <!-- Password  -->
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" placeholder="Enter your password" ngModel required
      #password="ngModel" minlength="6">
    <ng-container *ngIf="password.touched">
      <p class="error" *ngIf="password.errors?.['required']">Password is required</p>
      <p class="error" *ngIf="password.errors?.['minlength']">Password must be at least
        {{password.errors?.['minlength']['requiredLength']}} characters!</p>
    </ng-container>

    <!-- Repeat password  -->
    <label for="confirm-password">Confirm Password:</label>
    <input type="password" id="repeatPassword" name="repeatPassword" placeholder="Confirm your password" ngModel
      required #repeatPassword="ngModel">

    <ng-container *ngIf="repeatPassword.touched">
      <p class="error" *ngIf="repeatPassword.errors?.['required']">Repeat password is required</p>
    </ng-container>


    <input type="submit" value="Register" *ngIf="!form.invalid">
    <input type="submit" value="Register" *ngIf="form.invalid" disabled style="background-color: grey;">
    <p class ="error" *ngIf="error">{{error}}</p>
    <button class="login-button" routerLink="/login">Login</button>
  </form>
</div>
