// React/Project/client/Car-Shop/src/components/User/Login.jsx
import '../styles/User/Login.css';
import useForm from '../../hooks/useForm';
import { useContext } from 'react';
import AuthContext from '../../contexts/authContext';
export default function Login() {

    const isFormValid = () => {
        return values.username.trim() !== '' && values.password.trim() !== '';
    };
    const {
        loginSumbitHandler,
        error
    } = useContext(AuthContext)
    const { values, onChange, onSubmit } = useForm(loginSumbitHandler, { username: '', password: '' });

    return (
        <form className="login-form" onSubmit={onSubmit}>
            <h2>Login</h2>

            <label htmlFor="login-username">Username</label>
            <input
                type="text"
                id="login-username"
                name="username"
                value={values.username}
                onChange={onChange}
                required
            />

            <label htmlFor="login-password">Password</label>
            <input
                type="password"
                id="login-password"
                name="password"
                value={values.password}
                onChange={onChange}
                required
            />

            <button type="submit" disabled={!isFormValid()}>
                Login
            </button>
            {error && (
                <div className='login-error-container'>
                    <p className='error'>{error}</p>
                </div>
            )}
        </form>
    );
}

// Angular/Project/Crypto/src/app/user/login/login.component.ts
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  login(form: NgForm):void{
    console.log(form.value)
  }
}

<div class="container">
  <h2>Login Form</h2>

  <form #form="ngForm" (ngSubmit)="login(form)">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" placeholder="Enter your username" ngModel required>

    <label for="password">Password:</label>
    <input type="password" id="password" name="password" placeholder="Enter your password" ngModel required>

    <input type="submit" value="Login">
    <button class="register-button" routerLink="/register">Register</button>
  </form>
</div>
